### DISCUSSION TITLE
Move directories

### DISCUSSION THREAD

**Discussion by emiham** [gtronset/beets-filetote#143] [General]
I'd like to move all subdirectories as they are, regardless of what they are named. Right now my config is 
```yaml
filetote:
  extensions: .* "*"
```
which just moves all files in subdirectories to the parent directory. Is there a way to to do this? It seems like patterns should be the way, but it's not clear if you can or should make a pattern to match all directories.

**Comment by gtronset** [comment]
Hi @emiham! There's not an "easy button" for this right now; however, if your subfolders are consistent/predictable, `patterns` would be able to accomplish retaining subfolders in the final album location. For example, if you know the subfolders will always be an `artwork` folder and an `other` folder, you should be able to do something like this:

```
filetote:
  paths:
    pattern:artworkdir: $albumpath/artwork/$old_filename
    pattern:otherdir: $albumpath/other/$old_filename
  patterns:
    artworkdir:
      - "artwork/"
    otherdir:
      - "other/"
```

You should be able to extrapolate from here depending on your subfolder needs. Otherwise, if the subfolder could be anything and you want to preserve that, I'd need to look into adding that as a feature. I hope this helps!
