### ISSUE TITLE
ext:.*: $albumpath/artwork/ not working?

### ISSUE THREAD

**Issue by bob-no-much-code** [gtronset/beets-filetote#148]
Hi thanks for making this!
I'm trying to move all files to /artwork folder except lyrics or cover.jpg.
```
ext:.*: $albumpath/artwork/$old_filename
```
Does not seem to work used in this config:
```
filetote:
  exclude: .cue .m3u
  extensions: .txt .log .md5 .jpg .JPG .png .PNG .jpeg .JPEG
  patterns:
    artworkdir:
      - "[sS]cans/"
      - "[aA]rtwork/"
      - "[aA]lbum [aA]rt/"
      - "[aA]rt/"
      - "[cC]over/"
      - "[cC]overs/"
      - "[eE]xtra/"
  pairing:
    enabled: true
    extensions: ".lrc"
  paths:
    filename:cover.jpg: $albumpath/cover.jpg
    paired_ext:.lrc: $albumpath/lyrics/$medianame_old
    pattern:artworkdir: $albumpath/artwork/$old_filename
    ext:.*: $albumpath/artwork/$old_filename
```

What am I doing wrong?
