### ISSUE TITLE
Wildcard pattern looks in subfolders despite separate declaration

### ISSUE THREAD

**Issue by swills1** [gtronset/beets-filetote#159]
I have Filetote set up like this;

```
filetote:
  paths:
    pattern:scans: $albumpath/scans/$old_filename
    pattern:cover: $albumpath/${album}_cover
    pattern:cue: $albumpath/${album}_cue
    pattern:log: $albumpath/${album}_log
    pattern:m3u: $albumpath/${album}_m3u
  patterns:
    scans:
      - "[sS]cans/"
    cover:
      - "*.jpg"
    cue:
      - "*.cue"
    log:
      - "*.log"
    m3u:
      - "*.m3u"
 ```

Whenever `- "[sS]cans/"` contains jpg files, the `cover` pattern above takes precedent. Meaning, when jpg files exist under the scans folder, the scan folder isn't moved. Instead, the individual files end up  following this - `pattern:cover: $albumpath/${album}_cover`.

Is there a declaration or setting I've overlooked to prevent this? Essentially, if jpg files exist under a scans folder - I want that entire folder moved. Any jpg file under the main album folder should follow the `*.jpg` declaration.

Thanks for the work on this plugin. I really like how it carries over the functionality from extrafiles.
