### ISSUE TITLE
Query: Import of lrc files

### ISSUE THREAD

**Issue by arogl** [gtronset/beets-filetote#86]
Hi,

I have the following relevant config set in my config.yaml, but the lrc files did not get moved:

```yaml
plugins: 
  filetote
  
paths:
  default: %upper{%asciify{%left{$first_artist,1}}}/$first_artist/($year) $album%aunique{}/$album - $track - $artist - $title
  singleton: Singles/$artist - $title
  albumtype:soundtrack: Soundtracks/($year) $album%aunique{}/$album - $track - $artist - $title
  albumartist:\“Weird\ Al\” Yankovic: W/Weird Al Yankovic/($year) $album%aunique{}/$album - $track - $artist - $title
  albumartist:various\ artists: Various Artists/($year) $album%aunique{}/$album - $track - $artist - $title
  albumartist:various: Various Artists/($year) $album%aunique{}/$album - $track - $artist - $title
  comp: Various Artists/($year) $album%aunique{}/$album - $track - $artist - $title
  ext:.pdf: %upper{%asciify{%left{$first_artist,1}}}/$first_artist/($year) $album%aunique{}/$album - 00 - $artist - $title
  paired_ext:.lrc: %upper{%asciify{%left{$first_artist,1}}}/$first_artist/($year) $album%aunique{}/$artist - $track - $title.lrc

filetote:
  pairing:
    enabled: true
    pairing_only: true
    extensions: ".lrc"
  extensions: .pdf
  ```
  
  The original files were named as `$track - $title.[mp3|lrc]`
  
  What have set up incorrectly?

**Comment by gtronset** [comment]
Hi @arogl! Can you please share a few additional details for me? For example, what command are you using? Is the source/original folder pretty "flat", meaning the MP3 files and lyric ones are all side-by-side? If possible, it'd be great get an example of the folder and its contents.

Separately, are you looking to bring along just the lrc's with the MP3's or also PDFs? And did any of them move/copy over?

**Comment by arogl** [comment]
> Hi @arogl! Can you please share a few additional details for me? For example, what command are you using? Is the source/original folder pretty "flat", meaning the MP3 files and lyric ones are all side-by-side? If possible, it'd be great get an example of the folder and its contents.
> 
> Separately, are you looking to bring along just the lrc's with the MP3's or also PDFs? And did any of them move/copy over?

folder/file format:
Folder/Artist1/album1
	01 - The Way I Do.lrc
	01 - The Way I Do.mp3
Folder/Artist1/album2
	01 - Title1.lrc
	01 - Title1.mp3
	02 - Title2.lrc
	02 - Title2.mp3
Folder/Artist2/album3
	01 - Title1.lrc
	01 - Title1.mp3
Folder/Artist3/album4
	01 - Title1.lrc
	01 - Title1.mp3

From the Folder directory:

```sh
beet imp .
```

3 Artists, 4 albums, all of the mp3 files were moved, I had no PDF files in this list. The lrc files were left in the structure

**Comment by gtronset** [comment]
@arogl Thank you for the details! That helped to rule out a lot, actually. This is actually failing in the moving stage due to renaming (due to some differences in how Filtote renames vs. how Beets does for media, see below). The good news is this should be able to be simplified in your config with the following edit:

Update `paired_ext:.lrc: ...` to `paired_ext:.lrc: "$albumpath/$medianame_new"`. This will basically tell Filetote to key off of the naming rules you used for the MP3 file and simply adapt it for the LRC you're bringing along.

Out of curiosity, how/where are you getting `$first_artist`? Is that being set as an `item_field` by the `inline` plugin?

For some context, Filetote renaming is based on simpler rules than the regular renaming for Beets and has a couple of considerations (at least at this time), including `%aunique` not being available and a limited subset of the available fields from the media file (see README for the exact list). These are of course expandable based on needs, but there hasn't been a pressing need to add more since most use cases I've seen can leverage the media file's naming scheme. That said, please let me know if more flexibility is needed!

**Comment by arogl** [comment]
``$first_artist`` is a long regex I have.

```yaml
item_fields:
  first_artist: |
    import re
    artistlist = ["list of artists who", "really are duos", "and not just featuring artists"]
    return re.split(r'(?i)(,\s)|(;\s)|(\s&\s)|(\sfeat)|(\sft\.)|(\sft\ )',albumartist,1)[0:1][0] if albumartist not in artistlist else albumartist
 ```

With the ``"$albumpath/$medianame_new"`` It will pick up the ``%aunique``, but the file name I want for the lrc is ``$artist - $track - $title``. 

Is that possible?

**Comment by gtronset** [comment]
@arogl not right now, unfortunately. If the media file uses that exact format, you can use `$medianame_new` to clone the music file's name, but currently, there's only a small subset of fields available, and `$track` and `$title` are not in that list. Let me look to see what I can do about that, though 😄

**Comment by gtronset** [comment]
@arogl I just pushed up `v0.4.1`--can you please give it a go and see if that works or if you have any issues? From your above comments, I think you'll want to use: `$albumpath/$artist - $track - $title`.

**Comment by arogl** [comment]
> @arogl I just pushed up `v0.4.1`--can you please give it a go and see if that works or if you have any issues? From your above comments, I think you'll want to use: `$albumpath/$artist - $track - $title`.

I have set this up as suggested, however the padding of `$track` is lost e.g.:
```
A Special Place - 01 - My Artist - A Special Place.mp3
My Artist - 1 - A Special Place.lrc
```

config:
```yaml
paths:
  default: %upper{%asciify{%left{$first_artist,1}}}/$first_artist/($year) $album%aunique{}/$album - $track - $artist - $title
  paired_ext:.lrc: $albumpath/$artist - $track - $title
```
